### ISSUE TITLE
ChromeDriver support for Chrome v93

### ISSUE THREAD

**Issue by avatarworf** [breuerfelix/chromedriver-py#11]
Latest ChromeDriver support up to version v92

v93.0.4577 of Chrome was released on the 31st of August, so chromedriver_py support isn't currently available.

**Comment by breuerfelix** [comment]
thanks for the hint, maybe travis stopped working and i should switch to github actions for this project :) i will have a look into this, thanks!

**Comment by breuerfelix** [comment]
@avatarworf i programmed the workflow so i can manually trigger a specific version via environment as a github action now. i updated all v93 and a missing 92 version! also the brand new v95 got added today :)
if you are still missing a version, let me know, i can add it within minutes from everywhere!
