### ISSUE TITLE
Exception: Couldn't find a binary for your system: Darwin / arm64

### ISSUE THREAD

**Issue by lundstrj** [breuerfelix/chromedriver-py#13]
Exception: Couldn't find a binary for your system: Darwin / arm64. Please create an Issue on github.com/breuerfelix/chromedriver-py and include this Message.

This was attempted on a MBA M1 with Python 3.9.4 (I am helping a coworker setup my tool on this machine). The system is clearly Darwin and the machine is "arm64" so I'd assume that path simply isn't a file. As to why that is, I do not know. 

I noticed you simplified the logic regarding M1 somewhat recently, could that have caused a regression?

I myself am on an identical machine and I do not have this issue (but I know my coworker has also setup Python 2.7 on his box (due to reasons)) so it isn't as bog standard as my own setup.

I'd be happy to help debug this, I just don't know what would be of use to us.

**Comment by lundstrj** [comment]
I tried downgrading to older versions of chromedriver-py and 95.0.4638.17 works OK, anything newer does not.

**Comment by breuerfelix** [comment]
thanks for the issue! i identified the problem... the m1 binary is not included in the package since i forgot to put it in the manifests file... the bad part: i can't fix already uploaded versions so you will need to wait for a new chromedriver version to come out :/

**Comment by breuerfelix** [comment]
@lundstrj in this version the m1 isnt included aswell but since it is the old code it will use the x64 binary and runs this one through rosetta which might be a little slower. this is a workaround but once the new version is out it will perform faster on arm :)

**Comment by lundstrj** [comment]
You made quick work of this, well done. Thank you for being so responsive and also for authoring this tool.

**Comment by breuerfelix** [comment]
de nada :) thanks for those detailed issues, it makes fixing things way easier!

**Comment by mandrigin** [comment]
it looks like it failed to deploy to pypi
> File already exists. See https://pypi.org/help/#file-name-reuse for more information.

we are also very much looking forward to this fix, we **just** got an M1 mac for a new team member

**Comment by breuerfelix** [comment]
@lundstrj @mandrigin can you test version `97.0.4692.37` ?

**Comment by lundstrj** [comment]
Sure thing. I'll give it a go.
