### ISSUE TITLE
Chrome-stable is v96, but this Chromedriver-py doesn't support

### ISSUE THREAD

**Issue by greattypo** [breuerfelix/chromedriver-py#15]
Google-chrome-stable is currently at version 96: https://www.ubuntuupdates.org/pm/google-chrome-beta .. but I can't figure out why this command doesn't work:

`pip3 install chromedriver-py==96.0.4664.110
`

Response:
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement chromedriver-py==96.0.4664.110 (from versions: 2.38, 2.45.2, 2.45.3, 2.46, 78.0.3904.11, 78.0.3904.70, 79.0.3945.16, 79.0.3945.36, 80.0.3987.16, 81.0.4044.20, 81.0.4044.69, 83.0.4103.14, 83.0.4103.39, 84.0.4147.30, 85.0.4183.38, 85.0.4183.83, 85.0.4183.87, 86.0.4240.22, 87.0.4280.20, 87.0.4280.88, 88.0.4324.27, 88.0.4324.96, 89.0.4389.23, 90.0.4430.24, 91.0.4472.19, 92.0.4515.43, 92.0.4515.107, 93.0.4577.15, 93.0.4577.63, 94.0.4606.41, 95.0.4638.10, 95.0.4638.17, 97.0.4692.20, 97.0.4692.36, 97.0.4692.37)
ERROR: No matching distribution found for chromedriver-py==96.0.4664.110
```

chromedriver-py has been updated recently and seems to support v97.. did it just skip v96? Thanks for any help in clarifying.

**Comment by breuerfelix** [comment]
thanks for mentioning this :) to be honest, i do not know why my update script skipped all 96 versions.. i will investigate this once i got more time but i triggered the pipeline manually for these versions and all of them are pushed :)

`96.0.4664.110` this exact version does not exist for the chromedriver but there are other 96 versions which should work :) https://pypi.org/project/chromedriver-py/#history

**Comment by greattypo** [comment]
Amazing - thank you! Love this project :)
