### ISSUE TITLE
Do we want logic to handle chrome - chromedriver-py missmatch?

### ISSUE THREAD

**Issue by lundstrj** [breuerfelix/chromedriver-py#18]
Hello,

Long time fan by the way.

I've written a bit of logic to handle the times when my version of Chrome is higher than the current latest version that chromedriver-py can offer. Sometimes an outdated but still very recent version of chromedriver will still get the job done so I wrote code to handle that for my users.

Maybe other people would find that useful too?

I'd be happy to work with you to adapt my code to fit into this project.

**Comment by breuerfelix** [comment]
Hey @lundstrj , thanks mate :)

well currently I don't do any version comparisons in my package and the user has to manually install the correct chromedriver version by himself so right now i don't really know how your check looks like but it would be awesome if you could just create a PR with your changes and we can look over it :)
And then we can still determine whether we merge it or improve it a little bit ! but contributions are always welcome!

**Comment by lundstrj** [comment]
I imagine this would be a little install helper. I have code to check what version of chrome you have installed and then looks for a matching chromedriver-py version. If there is no matching version available and if your chrome version is higher than the current highest version of chromedriver-py, I also offer the user to try a lower version number of chromedriver-py as that sometimes still will let you run your selenium code. But yeah, let's make a PR.

**Comment by lundstrj** [comment]
Better late than never. https://github.com/breuerfelix/chromedriver-py/pull/21

**Comment by RileyXX** [comment]
This is my code for the chrome version check which supports Windows, Linux and MacOS. Tested and working on Windows, untested on Linux and MacOS. 

```
def get_chrome_version():
    system = platform.system()
    if system == 'Windows':
        from winreg import ConnectRegistry, HKEY_CURRENT_USER, OpenKey, QueryValueEx

        try:
            registry = ConnectRegistry(None, HKEY_CURRENT_USER)
            key = OpenKey(registry, r'Software\Google\Chrome\BLBeacon')
            version, _ = QueryValueEx(key, 'version')
            return version.split('.')[0]
        except:
            return None

    elif system == 'Darwin':
        try:
            plist_path = '/Applications/Google Chrome.app/Contents/Info.plist'
            with open(plist_path, 'rb') as plist_file:
                plist_content = plist_file.read().decode('utf-8')
            version_start = plist_content.index('<key>CFBundleShortVersionString</key>') + 38
            version_end = plist_content.index('</string>', version_start)
            return plist_content[version_start:version_end].split('.')[0]
        except:
            return None

    elif system == 'Linux':
        try:
            process = subprocess.run(['google-chrome', '--version'], capture_output=True, text=True)
            version = process.stdout.strip().split(' ')[2].split('.')[0]
            return version
        except:
            return None

    return None
```

Been running as part of my project that uses chromedriver for some time now and no issues to report from users. Code is based on: https://github.com/RileyXX/IMDB-Trakt-Syncer/blob/main/IMDBTraktSyncer/checkChromedriver.py
https://github.com/RileyXX/IMDB-Trakt-Syncer/blob/main/IMDBTraktSyncer/checkChromedriver.py

**Comment by breuerfelix** [comment]
The problem is, that i can't add this code to this repo since this would need to fit into another package. otherwhise this would be a "meta" package ...
if you bundle a python app, it always has pinned versions, so you cannot really install a different version afterwards.

But thanks for sharing the code! maybe i can put it into the readme :)
