### ISSUE TITLE
Example code fails

### ISSUE THREAD

**Issue by cramik** [breuerfelix/chromedriver-py#19]
Directly copied and ran example code using Python 3.10.2,

`C:\Users\Cramik\Desktop>python test4.py
Traceback (most recent call last):
  File "C:\Users\Cramik\Desktop\test4.py", line 4, in <module>
    service_object = Service(binary_path)
NameError: name 'Service' is not defined`

**Comment by cramik** [comment]
oh, just checked. Looks same as https://github.com/googleworkspace/python-samples/issues/49#issue-377112546

I'd suggest trying a new clean install and maybe a windows system in an attempt to reproduce.

**Comment by breuerfelix** [comment]
the problem here is not the binary_path but the Service() object / function you try to use. This has nothing to do with the library but with the code that uses the binary path :)

**Comment by dlutsch** [comment]
@breuerfelix I have the same issue. The Service() object is used in your example code but not defined, so I'm unsure of the type of object I need to be passing.

**Comment by breuerfelix** [comment]
uff this is true, now i realised! @lundstrj you update the docs, would you mind fixing the import aswell ? :) otherwhise i am going to have a look at it

**Comment by lundstrj** [comment]
Hello, I can take a stab at it =)

**Comment by breuerfelix** [comment]
thanks about that :)
