### ISSUE TITLE
Couldn't find a binary for your system: darwin / arm64.

### ISSUE THREAD

**Issue by xaptronic** [breuerfelix/chromedriver-py#22]
Hello! After a recent chromedriver version bump, I am getting this message:

`Couldn't find a binary for your system: darwin / arm64.`

It appears that since `106.0.5249.61` the zip file name is now `chromedriver_mac_arm64` instead of `chromedriver_mac_m1`.

Happy to help contribute a patch to help out.

![image](https://user-images.githubusercontent.com/479673/194637011-02ab82c9-6715-4cdd-9921-4faf1447cfbd.png)

vs

![image](https://user-images.githubusercontent.com/479673/194637164-f7b169e8-a41d-4209-b858-6d08f3097432.png)

**Comment by breuerfelix** [comment]
wow, why the fuck are they always updating their names :D this is annoying and hard to automate, but thanks for the hint, this is an easy fix :) next versions will have the arm binary again!

**Comment by breuerfelix** [comment]
can you try version 107.0.5304.19 ?

**Comment by xaptronic** [comment]
yes, will try when my macosx chrome updates to 107 (it's still at 106) - thanks!

**Comment by xaptronic** [comment]
We're all good - tysm!
