### ISSUE TITLE
chromdriver_py binary missing after running pyinstaller

### ISSUE THREAD

**Issue by legobumb** [breuerfelix/chromedriver-py#26]
After running pyinstaller to create an exe of my project and running the .exe that pyinstaller spits out, I get the error: "Couldn't find a binary for your system: windows / amd64. Please create an Issue on github.com/breuerfelix/chromedriver-py and include this Message." I have an AMD Ryzen 7 7600X processor and I'm on Windows 11 if that matters. The issue comes from the line in my code below

>"File "main.py", line 20, in <module>
>    from chromedriver_py import binary_path

I'm not sure what breaks between before running pyinstaller and after, but the chromdriver_py binary seems to not get packaged with the .exe and placing the chromedriver.exe file into the dist or main folders that pyinstaller create for me, doesn't seem to work. Googling the error I quoted at the beginning only leads me here to where someone had a similar issue, but with an M1, which isn't my system. If you have any ideas, that'd be fantastic.

**Comment by legobumb** [comment]
I managed to get around this issue by using a different python to executable module - specifically cx_freeze in this case.

**Comment by breuerfelix** [comment]
@legobumb thanks for the updates, i was not having the time to investigate this issue anyways but it seems like the packer is not able to package external files (which are not envoy files). glad that it works with a different one!
