### ISSUE TITLE
Missing release for Chrome 115?

### ISSUE THREAD

**Issue by RileyXX** [breuerfelix/chromedriver-py#30]
I noticed Chrome 115 has launched recently but still don't see it as part of chromedriver-py releases. https://pypi.org/project/chromedriver-py/#history. 

~~Could there be a bug?~~

~~Where does chromedriver-py pull releases from?~~

Edit: I see now it is probably not a bug. Chrome version 115 is just not listed in their api yet https://chromedriver.storage.googleapis.com/

**Comment by breuerfelix** [comment]
seems like 115 is still not released... do you know if they have a new api? or is this version just not available?
i can't find anything on the web

**Comment by RileyXX** [comment]
After looking at it, looks like according to https://chromedriver.chromium.org/downloads they might have changed the API for versions 115 and newer.

"If you are using Chrome version 115 or newer, please consult [the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading."

"Consult [our JSON API endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints) if you’re looking to build automated scripts based on Chrome for Testing release data."

**Comment by RileyXX** [comment]
I asked chatgpt to modify some things so take the following with a grain of salt.

Modified `chromedriver_py /__init__.py` with added support for win64 :

```
import os
import platform

_BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def _get_filename():
    path = os.path.join(_BASE_DIR, "chromedriver_")
    machine = platform.machine().lower()

    sys = platform.system().lower()
    if sys == "windows":
        if "64" in machine:
            path += "win64.exe"  # Use the 64-bit binary for Windows
        else:
            path += "win32.exe"  # Default to 32-bit binary for Windows
    elif sys == "darwin":
        path += "mac"
        if "arm" in machine:
            path += "_arm64"
        else:
            path += "64"
    elif sys == "linux":
        if machine.endswith("32"):
            raise Exception("Google doesn't compile 32bit chromedriver versions for Linux. Sorry!")
        if "arm" in machine:
            raise Exception("Google doesn't compile chromedriver versions for Linux ARM. Sorry!")
        path += "linux64"
    else:
        raise Exception("Could not identify your system: " + sys)

    if not path or not os.path.isfile(path):
        msg = "Couldn't find a binary for your system: " + sys + " / " + machine + ". "
        msg += "Please create an Issue on github.com/breuerfelix/chromedriver-py and include this Message."
        raise Exception(msg)

    return path


binary_path = _get_filename()

```

**Comment by breuerfelix** [comment]
thanks :) well since they now provide a json api, i will rewrite the updater anyways, its way easier to use a json api :)

problem is: i am on vacation till sunday so this fix might wait till next week... thanks for your investigation! that helped me a lot :) expect new versions next week!

**Comment by RileyXX** [comment]
Very cool good to hear and thanks for the update! Yeah json is definitely a better approach. Nice to see they switched over. Thankfully it looks like chromedriver 114 is working fine on chrome 115 so this shouldn't be an issue for existing projects. 

Enjoy your vacation!

**Comment by breuerfelix** [comment]
@RileyXX fixed it :) it now uses the new api, but i rewrote the whole script :D chatgpt is not the best option for this kind of task :D

but thanks for suggesting the new api / repo, that was helpful since i didnt have to research it myself :)

could you test the new 115 version? if some version in between was missing, just let me know and i will update it. from now on the pipeline should catch new versions and publish them asap!

**Comment by RileyXX** [comment]
Yeah ChatGPT can be hit or miss. 

Glad the API info was useful.

I just tested the latest chromedriver-py release (115) and all seems to be working good on my projects. Nicely done and thanks for the quick fix! 👍

**Comment by breuerfelix** [comment]
awesome, thanks for the fast feedback!
