### ISSUE TITLE
Latest chrome versions don't appear to be getting added on PyPI

### ISSUE THREAD

**Issue by RileyXX** [breuerfelix/chromedriver-py#39]
Latest chrome versions don't appear to be getting added on PyPI.

chromedriver-py PyPI release history: https://pypi.org/project/chromedriver-py/#history

Latest version available currently on chromedriver-py PyPI page is `120.0.6099.109` _Dec 18, 2023_.

According to https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json the latest stable version is `121.0.6167.85` as well as dev and beta builds for 122 and 123.

I just noticed this today haven't had much time to look into it. I'm not sure if the latest stable build was just pushed recently to JSON or something. If so there might just be a delay in the PyPI package update. But I did do a google search and 121 stable apparently released Jan 17th so I'm not 100% sure if there is an issue with the project updating or not but might be worth checking. I'll check back on this soon.

**Comment by breuerfelix** [comment]
@RileyXX its running again! i won't update all missing versions in between (since i covered all major ones). If you need a specific version, ping me here with the ones so i can start actions which will upload those :) Thats a no brainer once i have the versions!
