### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 85

### ISSUE THREAD

**Issue by frankstallone** [breuerfelix/chromedriver-py#4]
Chrome seems to think I am on the latest, 84, and yet the latest chromedriver_py only supports 85.  How do I resolve this? How do I reconcile this?

<img width="387" alt="Screen Shot 2020-08-24 at 4 32 18 PM" src="https://user-images.githubusercontent.com/496730/91093407-61f85880-e627-11ea-8aee-fad027b4bd26.png">

**Comment by breuerfelix** [comment]
pretty interesting... so chromedriver is newer than the actual chrome :D

resolving this is pretty easy. just head over here: https://pypi.org/project/chromedriver-py/#history  
and then pick the appropiate version which is 84 in your case. click it, and on the top you get the pip install command for this version which is in your case: `pip install chromedriver-py==84.0.4147.30`

and voila, that should work :)

**Comment by frankstallone** [comment]
Perfect! I figured there would be a way to specify a version but did not find it in the docs. That worked, thank you!
