### ISSUE TITLE
release beta versions of chromedriver as prereleases

### ISSUE THREAD

**Issue by DetachHead** [breuerfelix/chromedriver-py#42]
i work in a project that uses both selenium and playwright, as we've been gradually migrating to playwright but still have old tests that use selenium. as a result, the version of chromedriver we use needs to match [the version of chrome bundled with playwright](https://playwright.dev/python/docs/release-notes#browser-versions).

we used to have our own chromedriver installer script to handle this for us, but switching to chromedriver-py has made this process much simpler. however i noticed today that the version of chrome bundled with the latest playwright release is 128, which [does not yet have a stable chromedriver release](https://googlechromelabs.github.io/chrome-for-testing/), meaning we can't yet update our version of playwright because the latest version of chromedriver-py is still 127.

it would be nice if releases from the beta channel were also published to pypi as a [prerelease](https://pythonpackaging.info/07-Package-Release.html#Versioning-your-code) so we don't have to wait for the stable release.

**Comment by KotlinIsland** [comment]
why not all channels?
