### ISSUE TITLE
chromedriver.exe version is ahead of publicly released Chrome browser version

### ISSUE THREAD

**Issue by JeromeHoen** [breuerfelix/chromedriver-py#5]
HI! Thanks for your package. I have an issue right now. The latest chromedriver.exe that is downloaded is in version 89, but Chrome is still in 88 and 89 is still in beta and I cannot update it. Is there something else I can do?

**Comment by breuerfelix** [comment]
hey !

you can have a look at other versions of the package here: https://pypi.org/project/chromedriver-py/#history  
in your example you can choose https://pypi.org/project/chromedriver-py/88.0.4324.96/ which you can install like this:
```bash
pip install chromedriver-py==88.0.4324.96
```
